version: '1.00.1'
services:
  mongodb:
    image: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  Backend:
    build: .
    image: radware_server
    container_name: radware_server
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL = mongodb://mongodb:27017/fullstack-app
      - PORT = 5000
volumes:
  mongodb_data: